# Generated by Django 3.0.3 on 2020-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('cat_img', models.ImageField(default='default.png', upload_to='category_list')),
                ('category_active', models.BooleanField(default=True)),
            ],
        ),
    ]
