# Generated by Django 3.0.3 on 2020-02-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='category_table',
            name='cname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
